# Generated by Django 3.2.5 on 2021-08-17 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/picture')),
                ('create', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
